### ISSUE TITLE
Cant see the picoder

### ISSUE THREAD

**Issue by Angelus022695** [sbcshop/PiCoder-Software#1]
Windows 11 doesnt detect the picoder

**Comment by sbcshop3** [comment]
When you connect pico W of PiCoder with micro USB in normal mode then it is only visible in Thonny IDE, Did you check in Thonny IDE as shown in below image,
![picoder_pico](https://github.com/sbcshop/PiCoder-Software/assets/129948335/01c4f50d-2000-4bcf-b685-dc5f56e643a0)
